create table users (
  id bigint generated by default as identity primary key,
  username text,
  firstname text,
  lastname text,
  avatar text,
  badges int,
  checkins int,
  beers int,
  last_updated timestamp with time zone
);

create table breweries (
  id bigint generated by default as identity primary key,
  name text,
  slug text,
  type text,
  label text,
  city text,
  state text,
  country text,
  lat numeric,
  lng numeric,
  hads int,
  total_rating numeric,
  average numeric
);

create table beers (
  id bigint generated by default as identity primary key,
  name text,
  slug text,
  label text,
  style text,
  abv numeric,
  brewery bigint references breweries,
  last_had timestamp with time zone,
  hads int,
  total_rating numeric,
  average numeric
);

create table venues (
  id bigint generated by default as identity primary key,
  name text,
  slug text,
  address text,
  city text,
  state text,
  country text,
  lat numeric,
  lng numeric,
  hads int,
  total_rating numeric,
  average numeric
);

create table checkins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  comment text,
  rating numeric(4,2) check (rating >= 0 and rating <= 5),
  beer bigint references beers,
  brewery bigint references breweries,
  venue bigint references venues
);